server:
  port: 9095

spring:
  application:
    name: api_gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-service:9090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    console: ${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}
  level:
    root: INFO
    com:
      ps:
        backend: DEBUG
  file:
    name: /logs/${spring.application.name}.log
    max-size: 10MB
    max-history: 30
    total-size-cap: 1GB

jwt:
  secret: ${JWT_SECRET}