spring:
  application:
    name: config-server
  kafka:
    bootstrap-servers: localhost:29092
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PratapShishodia/Ecommerce_Config_server.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          username: PratapShishodia
          password: ${GIT_TOKEN}
server:
  port: 9071
management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  pattern:
    console: ${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}
  level:
    root: INFO
    com:
      ps:
        backend: DEBUG
  file:
    name: /logs/${spring.application.name}.log
    max-size: 10MB
    max-history: 30
    total-size-cap: 1GB